spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kong0369   # ⚠️ 본인 비밀번호로 변경

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

konghome:
  jwt:
    secret: "change-this-to-a-very-long-random-secret-key-please"
    access-exp-min: 15
    refresh-exp-days: 7


server:
  port: 8080
