spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.36.217:3306/konghome?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: konghome
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: dodejqn6@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

konghome:
  jwt:
    secret: ${SECRET}
    access-exp-min: 30
    refresh-exp-days: 7
  frontend-url: "https://konghome.kr"
  cors:
    allowed-origins:
      - "https://konghome.kr"

file:
  upload-dir: /app/uploads


server:
  port: 8080

app:
  env: blue
