spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kong0369

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: dodejqn6@gmail.com
    password: vgpxxukqecpjabmn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

konghome:
  frontend-url: "http://192.168.123.107:5173"
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://127.0.0.1:5173"
      - "http://192.168.123.107:5173"

file:
  upload-dir: C:/myweb/backend/backend/uploads
  
server:
  port: 8080
  address: 0.0.0.0
